version: "3"
services:

  go-service-prom:
    container_name: go-service-prom
    image: go-prometheus-app
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    depends_on:
      - go-service-prom

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - /var/log:/var/log

    ports:
      - 3000:3000
    depends_on:
      - prometheus